vcpkg.exe install zeromq
vcpkg.exe install zeromq:x64-windows
vcpkg.exe install jsoncpp
vcpkg.exe install jsoncpp:x64-windows
vcpkg.exe install cryptopp
vcpkg.exe install cryptopp:x64-windows
vcpkg.exe install Snappy
vcpkg.exe install Snappy:x64-windows
vcpkg.exe install OpenSSL
vcpkg.exe install OpenSSL:x64-windows
vcpkg.exe install ROCKSDB
vcpkg.exe install ROCKSDB:x64-windows
vcpkg.exe install Protobuf
vcpkg.exe install Protobuf:x64-windows
vcpkg.exe install pthreads
vcpkg.exe install pthreads:x64-windows
vcpkg.exe install libevent
vcpkg.exe install libevent:x64-windows
vcpkg.exe install benchmark
vcpkg.exe install benchmark:x64-windows
vcpkg.exe install CLI11
vcpkg.exe install CLI11:x64-windows
vcpkg.exe install GTest
vcpkg.exe install GTest:x64-windows
vcpkg.exe install yaml-cpp
vcpkg.exe install yaml-cpp:x64-windows
vcpkg install yasm-tool
vcpkg install yasm-tool:x64-windows
vcpkg install gmp
vcpkg install gmp:x64-windows
